services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 11434:11434
    volumes:
      - ./volumes/ollama:/root/.ollama
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    restart: unless-stopped
    networks:
      - 3rdparty

  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chromadb
    ports:
      - 8000:8000
    volumes:
      - ./volumes/chromadb:/chroma/chroma
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
    restart: unless-stopped
    networks:
      - 3rdparty
      
  docling:
    image: quay.io/docling-project/docling-serve:v1.3.1
    container_name: docling
    ports:
      - 5001:5001
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
    restart: unless-stopped
    networks:
      - 3rdparty

  redis:
    image: docker.io/valkey/valkey:8.0.1-alpine
    container_name: redis-valkey
    # volumes:
    #   - ./volumes/redis:/data
    command: "valkey-server --save 30 1"
    healthcheck:
      test: "[ $$(valkey-cli ping) = 'PONG' ]"
      start_period: 5s
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - 3rdparty

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
      - chromadb
      - docling
      - redis
    ports:
      - 3000:8080
    volumes:
      - ./volumes/open-webui:/app/backend/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - VECTOR_DB=chroma
      - CHROMA_HTTP_HOST=chromadb
      - CHROMA_HTTP_PORT=8000
      - ENABLE_WEBSOCKET_SUPPORT="true"
      - WEBSOCKET_MANAGER="redis"
      - WEBSOCKET_REDIS_URL="redis://redis:6379/1"
      - REDIS_KEY_PREFIX="open-webui"
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - 3rdparty

networks:
  3rdparty:
    external: true

